server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
#          从注册中心拉取动态路由
          enabled: true
      enabled: true
      routes:
        - id: service1router
          uri: lb://service-1
          predicates:
            - Path=/**
#            - name: Cookie
#              args:
#                name: mycookie
#                regexp: mycookievalue
    nacos:
      discovery:
        enabled: true
        server-addr: '127.0.0.1:8080'
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'gateway'