spring:
  profiles:
    active: dev
  application:
    name: service2
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: '127.0.0.1:8848'
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 6002
