spring:
  application:
    name: service-1
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: '127.0.0.1:8848'
server:
  port: 6001
management:
  endpoints:
    web:
      exposure:
        include: "*"